### ISSUE TITLE
Please invite me to tinderzone

### ISSUE THREAD

**Issue by cixtor** [tinderzone/tinderzone#18]
### Name

cixtor

### Why do you want to join this organization?

I have been an active member of the open-source community on GitHub and other platforms, and it is always a joy to find like-minded people willing to share knowledge and experiences. I would love to join thir GitHub organization to help many more developers become excellent open-source maintainers.

**Comment by thuongtruong109** [comment]
Hi @cixtor 
I have sent an invitation to you. Accept it and you are a member of this community!
Thank you and welcome!
